version: "3.9"
services:
  api:
    restart: always
    image: ghcr.io/noah-witt/trivia/api:dev
    build:
      target: api
      context: ./api/
    ports:
      - "127.0.0.1:9091:80"
    volumes:
      - ./api/trivia:/code/trivia:ro
    environment:
      - MONGODB_URL=mongodb://mongo/trivia?retryWrites=true&w=majority
    depends_on:
      - mongo
  ui:
    restart: always
    image: ghcr.io/noah-witt/trivia/ui:dev
    build:
      target: ui
      context: ./ui/
    ports:
      - "127.0.0.1:9092:80"
    volumes:
      - ./ui/:/code:ro
      - /code/node_modules
  nginx:
    restart: always
    image: nginx:1
    ports:
      - "127.0.0.1:9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - ui
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "127.0.0.1:9093:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=triviapass
