version: "3.9"
services:
  api:
    restart: always
    image: ghcr.io/noah-witt/trivia/api:latest
    build:
      target: prod
      context: ./api/
    environment:
      - MONGODB_URL=mongodb://mongo/trivia?retryWrites=true&w=majority
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
  ui:
    restart: always
    image: ghcr.io/noah-witt/trivia/ui:latest
    build:
      target: prod
      context: ./ui/
    volumes:
      - ./ui/:/code:ro
      - /code/node_modules
  nginx:
    restart: always
    image: nginx:1
    ports:
      - "127.0.0.1:9020:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - ui
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=triviapass
