version: "3.9"
services:
  api:
    restart: always
    image: ghcr.io/noah-witt/trivia/api:dev
    build:
      target: api
      context: ./api/
    ports:
      - "127.0.0.1:9091:80"
    volumes:
      - ./api/trivia:/code/trivia:ro
    environment:
      - MONGODB_URL=mongodb://mongo/trivia?retryWrites=true&w=majority
    depends_on:
      - mongo
  worker:
    restart: always
    image: ghcr.io/noah-witt/sfpd-log/api:dev
    build:
      target: api
      context: .
    entrypoint: pdm run watchfiles "celery --app sfpdlog.worker.celery worker --loglevel debug -Ofair" /code/
    volumes:
      - ./api/sfpdlog:/code/sfpdlog:ro
      - ./celery:/celery
    environment:
      - MONGODB_URL=mongodb://mongo/sfpdlog?retryWrites=true&w=majority
      - GEOCODIO_API_KEY=${GEOCODIO_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_KEY=${ADMIN_KEY}
    depends_on:
      - mongo
  worker-beat:
    extends: worker
    entrypoint: pdm run watchfiles "celery --app sfpdlog.worker.celery beat -s /celery/celerybeat-schedule --loglevel debug" /code/
  ui:
    restart: always
    image: ghcr.io/noah-witt/trivia/ui:dev
    build:
      target: ui
      context: .
    ports:
      - "127.0.0.1:9092:80"
    volumes:
      - ./ui/:/code:ro
      - /code/node_modules
  nginx:
    restart: always
    image: nginx:1
    ports:
      - "127.0.0.1:9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - ui
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "127.0.0.1:9093:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=triviapass
