version: "3.9"
services:
  api:
    restart: always
    image: ghcr.io/noah-witt/trivia/api:latest
    build:
      target: prod
      context: ./api/
    environment:
      - MONGODB_URL=mongodb://mongo/trivia?retryWrites=true&w=majority
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_SECRET=${TOKEN_SECRET}
    depends_on:
      - mongo
  nginx:
    restart: always
    image: ghcr.io/noah-witt/trivia/ui:latest
    build:
      target: prod
      context: ./ui/
    ports:
      - "127.0.0.1:9020:80"
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "127.0.0.1:9021:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=triviapass
