on: [push]

jobs:
  ci_job:
    runs-on: ubuntu-latest
    name: run ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: api ci
        run: docker build --target ci --tag ci:latest ./api && docker run --rm ci:latest
